language: en

# Pipeline components, check https://rasa.com/docs/rasa/components for more info
pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: SpacyEntityExtractor
    dimensions: [ CARDINAL, TIME ]
  - name: RegexEntityExtractor
    use_lookup_tables: true
  - name: DIETClassifier
    epochs: 100
    embedding_dimension: 50
    learning_rate: 0.001
    drop_rate: 0.2
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1

# Policies, check https://rasa.com/docs/rasa/policies/ for more info
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.4 
  - name: UnexpecTEDIntentPolicy
    max_history: 10
    epochs: 100
    constrain_similarities: true
  - name: TEDPolicy
    max_history: 10
    epochs: 100
    split_entities_by_comma: true
    constrain_similarities: true
